# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56e0fba689228072e232a9c91461ee9daf6a312eb4282bcbf4cd5400eeca32a41d9d842d1a5a91eb9f2c2914dd3915fd6d6a6821aef0d18e2b593e29ebf6122a

test:
  secret_key_base: 97c68d87bd6ec7c63458e29169d54c9552837667815e1460cfb94c6305882944926b96703d7d1c5a13f15fb6c7e5375c6880a6938250498600b6e140eb945475

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
